services:
  app:
    build: .
    container_name: stonkmarket-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed, or use an env_file
      # - MONGO_URI=your_mongo_uri
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: stonkmarket-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
